/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShelfNameRouteImport } from './routes/shelf/$name'
import { Route as Demo10mRouteImport } from './routes/demo/10m'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelfNameRoute = ShelfNameRouteImport.update({
  id: '/shelf/$name',
  path: '/shelf/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const Demo10mRoute = Demo10mRouteImport.update({
  id: '/demo/10m',
  path: '/demo/10m',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demo/10m': typeof Demo10mRoute
  '/shelf/$name': typeof ShelfNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demo/10m': typeof Demo10mRoute
  '/shelf/$name': typeof ShelfNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demo/10m': typeof Demo10mRoute
  '/shelf/$name': typeof ShelfNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/demo/10m' | '/shelf/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/demo/10m' | '/shelf/$name'
  id: '__root__' | '/' | '/login' | '/demo/10m' | '/shelf/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  Demo10mRoute: typeof Demo10mRoute
  ShelfNameRoute: typeof ShelfNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelf/$name': {
      id: '/shelf/$name'
      path: '/shelf/$name'
      fullPath: '/shelf/$name'
      preLoaderRoute: typeof ShelfNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/10m': {
      id: '/demo/10m'
      path: '/demo/10m'
      fullPath: '/demo/10m'
      preLoaderRoute: typeof Demo10mRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  Demo10mRoute: Demo10mRoute,
  ShelfNameRoute: ShelfNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
